name: easy_exchange
description: A currency exchange rate app.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  decimal: ^2.3.3
  rxdart: ^0.27.7
  provider: ^6.0.5
  fl_chart: ^0.65.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
          style: italic
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 800

  assets:
    - assets/images/
