// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2r2wq8tRir6XRSU6cwjLOOcri8AxBOuc',
    appId: '1:615902545487:web:cb3bdfd3e2a446bf428c3a',
    messagingSenderId: '615902545487',
    projectId: 'tasreef',
    authDomain: 'tasreef.firebaseapp.com',
    storageBucket: 'tasreef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLEGmfz4fMu97C7mqCRejjpKcWnsUYWDA',
    appId: '1:615902545487:android:0691ce8f2b8ac7b4428c3a',
    messagingSenderId: '615902545487',
    projectId: 'tasreef',
    storageBucket: 'tasreef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6RZORB3lL8KRfmUtchiA8AoJ1QSBgVJ0',
    appId: '1:615902545487:ios:6c1ac771c477c95c428c3a',
    messagingSenderId: '615902545487',
    projectId: 'tasreef',
    storageBucket: 'tasreef.firebasestorage.app',
    iosBundleId: 'com.example.easyExchange',
  );
}
